### ISSUE TITLE
SMPL data to Humanoid Skeleton

### ISSUE THREAD

**Issue by ethancohen123** [Zju-George/DeepMimic#2]
Hi, 
How do you manage to go from the SMPL data ( bvh file ) to the Humainoid Skeleton for DeepMimic ?
Thank you

**Comment by sxhzju** [comment]
![image](https://user-images.githubusercontent.com/33959089/71547523-f39dc080-29db-11ea-95a2-83eec5368747.png)
That is for retargeting in Unity

**Comment by sxhzju** [comment]
Simply put, the whole process is:

1. Use SMPL unity plugin to transfer the SMPL data into Unity.
2. Build an exactly same Humanoid Skeleton of DeepMimic in Unity according to the json file which describes the skeleton.
3. Retargeting in Unity.
4. Write the motions into json files and load them back to DeepMimic to train the policy.

**Comment by Zju-George** [comment]
![Uploading retargeting.gif…]()

**Comment by sxhzju** [comment]
![retargeting](https://user-images.githubusercontent.com/33959089/71547632-5fccf400-29dd-11ea-9aec-d5bc2ef68fb4.gif)
An example of retargeting.

**Comment by hellozjj** [comment]
> ![retargeting](https://user-images.githubusercontent.com/33959089/71547632-5fccf400-29dd-11ea-9aec-d5bc2ef68fb4.gif)
> An example of retargeting

The character is not moving forward. Is the result right? Or the original movement is also not going aheard? 
I am not familiar with CG or Unity.

**Comment by sxhzju** [comment]
@hellozjj 
Yep, the root joint is fixed. You can refer to [hmmr](https://github.com/akanazawa/human_dynamics) results.

**Comment by hellozjj** [comment]
> @hellozjj
> Yep, the root joint is fixed. You can refer to [hmmr](https://github.com/akanazawa/human_dynamics) results.

So we have to calculate the global root translation?

**Comment by sxhzju** [comment]
That's right!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hellozjj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 下午5:43
收件人:&nbsp;"Zju-George/DeepMimic"<DeepMimic@noreply.github.com&gt;;
抄送:&nbsp;"Zju-XiaohanSun"<470196540@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zju-George/DeepMimic] SMPL data to Humanoid Skeleton (#2)





  
@hellozjj
 Yep, the root joint is fixed. You can refer to hmmr results.
  
So we have to calculate the global root translation?

**Comment by hellozjj** [comment]
> That's right!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"hellozjj"<notifications@github.com&gt;; 发送时间:&nbsp;2020年3月30日(星期一) 下午5:43 收件人:&nbsp;"Zju-George/DeepMimic"<DeepMimic@noreply.github.com&gt;; 抄送:&nbsp;"Zju-XiaohanSun"<470196540@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [Zju-George/DeepMimic] SMPL data to Humanoid Skeleton (#2) @hellozjj Yep, the root joint is fixed. You can refer to hmmr results. So we have to calculate the global root translation? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

OMG, this is so complicated for whoever are not learning CG......[sad]

**Comment by sxhzju** [comment]
@hellozjj Haha, be patient, step by step, you will soon be a CG master!
btw, where are you from?

**Comment by hellozjj** [comment]
> @hellozjj Haha, be patient, step by step, you will soon be a CG master!
> btw, where are you from?

I'm from China. I am patient, but I don't think my leader is too. [摊手]

**Comment by sxhzju** [comment]
@hellozjj I'm from China, too! so 为啥 we 还要使用 English?

**Comment by hellozjj** [comment]
> @hellozjj I'm from China, too! so 为啥 we 还要使用 English?

哈哈哈哈， 可以用中文啊。 正好我英语也不怎么好。。。。

**Comment by hellozjj** [comment]
> @hellozjj I'm from China, too! so 为啥 we 还要使用 English?

B站关注你了哈。[膜拜大佬]

**Comment by sxhzju** [comment]
感谢，我是个菜鸡。。呜呜




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"hellozjj"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月30日(星期一) 晚上6:59
收件人:&nbsp;"Zju-George/DeepMimic"<DeepMimic@noreply.github.com&gt;;
抄送:&nbsp;"Zju-XiaohanSun"<470196540@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Zju-George/DeepMimic] SMPL data to Humanoid Skeleton (#2)





  
@hellozjj I'm from China, too! so 为啥 we 还要使用 English?
  
B站关注你了哈。[膜拜大佬]
 
—
You are receiving this because you commented.
Reply to&nbsp;发送this email directly, view it on GitHub, or unsubscribe.

**Comment by jiaqixuac** [comment]
> > That's right!
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "hellozjj"<[notifications@github.com](mailto:notifications@github.com)>; 发送时间: 2020年3月30日(星期一) 下午5:43 收件人: "Zju-George/DeepMimic"<[DeepMimic@noreply.github.com](mailto:DeepMimic@noreply.github.com)>; 抄送: "Zju-XiaohanSun"<[470196540@qq.com](mailto:470196540@qq.com)>;"Comment"<[comment@noreply.github.com](mailto:comment@noreply.github.com)>; 主题: Re: [Zju-George/DeepMimic] SMPL data to Humanoid Skeleton (#2) @hellozjj Yep, the root joint is fixed. You can refer to hmmr results. So we have to calculate the global root translation? — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> OMG, this is so complicated for whoever are not learning CG......[sad]

同在学习中，可以交流一下吗，Q1079206788

**Comment by jiaqixuac** [comment]
> > @hellozjj Haha, be patient, step by step, you will soon be a CG master!
> > btw, where are you from?
> 
> I'm from China. I am patient, but I don't think my leader is too. [摊手]

@hellozjj 
同在学习中，可以交流一下吗，Q1079206788

**Comment by Kismetzc** [comment]
嗨，@Zju-George
请问你知道如何将3D坐标数据转化为bvh文件吗？
