### ISSUE TITLE
关于论文复现的几个问题

### ISSUE THREAD

**Issue by hch1017** [Zju-George/DeepMimic#3]
老哥您好，我是一名大三学生，最近在学习DRL，看了您的工作我受益匪浅，百忙之中打扰您，想要咨询您几个问题。
1.论文中提到的multi-clip的设计层次我不是很明白，想要参考一下您的设计思路。
2.论文中提到的early termination是在项目代码中的哪一部分。
3.这个地方定义的root_reward是为什么而定义，它并未在论文中提到，而且它还分走了20%的权重。
![image](https://user-images.githubusercontent.com/43041058/77545024-c67e8280-6ee4-11ea-9aae-103c7a253b70.png)

如果您看到这里，那么不管您是否愿意做出回答，我都感谢您的阅读。
最后祝您和您的家人朋友在疫情期间平安健康！

**Comment by sxhzju** [comment]
sry but it's not my work but xbpeng's.
